# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

# from PyQt5 import QtCore, QtGui, QtWidgets
import aqt

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 533)
        self.main_layout = aqt.qt.QVBoxLayout(Dialog)
        self.main_layout.setObjectName("main_layout")
        self.tabWidget = aqt.qt.QTabWidget(Dialog)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = aqt.qt.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.gridLayout_4 = aqt.qt.QGridLayout(self.mainTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.syncBtn = aqt.qt.QPushButton(self.mainTab)
        self.syncBtn.setEnabled(False)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Fixed, aqt.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncBtn.sizePolicy().hasHeightForWidth())
        self.syncBtn.setSizePolicy(sizePolicy)
        self.syncBtn.setMinimumSize(aqt.QSize(100, 0))
        self.syncBtn.setObjectName("syncBtn")
        self.gridLayout_4.addWidget(self.syncBtn, 4, 4, 1, 1)
        self.deckLayout = aqt.qt.QHBoxLayout()
        self.deckLayout.setObjectName("deckLayout")
        self.deckLabel = aqt.qt.QLabel(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Fixed, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckLabel.sizePolicy().hasHeightForWidth())
        self.deckLabel.setSizePolicy(sizePolicy)
        self.deckLabel.setObjectName("deckLabel")
        self.deckLayout.addWidget(self.deckLabel)
        self.deckComboBox = aqt.qt.QComboBox(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Preferred, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckComboBox.sizePolicy().hasHeightForWidth())
        self.deckComboBox.setSizePolicy(sizePolicy)
        self.deckComboBox.setEditable(True)
        self.deckComboBox.setObjectName("deckComboBox")
        self.deckLayout.addWidget(self.deckComboBox)
        self.gridLayout_4.addLayout(self.deckLayout, 0, 0, 1, 5)
        self.horizontalLayout = aqt.qt.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = aqt.qt.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = aqt.qt.QLabel(self.mainTab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.newWordListWidget = aqt.qt.QListWidget(self.mainTab)
        self.newWordListWidget.setAlternatingRowColors(True)
        self.newWordListWidget.setSelectionMode(aqt.QAbstractItemView.SelectionMode.MultiSelection)
        self.newWordListWidget.setObjectName("newWordListWidget")
        self.verticalLayout.addWidget(self.newWordListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = aqt.qt.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(aqt.qt.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = aqt.qt.QLabel(self.mainTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.needDeleteWordListWidget = aqt.qt.QListWidget(self.mainTab)
        self.needDeleteWordListWidget.setAlternatingRowColors(True)
        self.needDeleteWordListWidget.setObjectName("needDeleteWordListWidget")
        self.verticalLayout_2.addWidget(self.needDeleteWordListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 5)
        self.apiLayout = aqt.qt.QHBoxLayout()
        self.apiLayout.setObjectName("apiLayout")
        self.apiLabel = aqt.qt.QLabel(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Fixed, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiLabel.sizePolicy().hasHeightForWidth())
        self.apiLabel.setSizePolicy(sizePolicy)
        self.apiLabel.setObjectName("apiLabel")
        self.apiLayout.addWidget(self.apiLabel)
        self.apiComboBox = aqt.qt.QComboBox(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Preferred, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiComboBox.sizePolicy().hasHeightForWidth())
        self.apiComboBox.setSizePolicy(sizePolicy)
        self.apiComboBox.setObjectName("apiComboBox")
        self.apiLayout.addWidget(self.apiComboBox)
        self.gridLayout_4.addLayout(self.apiLayout, 2, 0, 1, 5)
        self.dictionaryLayout = aqt.qt.QHBoxLayout()
        self.dictionaryLayout.setObjectName("dictionaryLayout")
        self.dictionaryLabel = aqt.qt.QLabel(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Fixed, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dictionaryLabel.sizePolicy().hasHeightForWidth())
        self.dictionaryLabel.setSizePolicy(sizePolicy)
        self.dictionaryLabel.setObjectName("dictionaryLabel")
        self.dictionaryLayout.addWidget(self.dictionaryLabel)
        self.dictionaryComboBox = aqt.qt.QComboBox(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Preferred, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dictionaryComboBox.sizePolicy().hasHeightForWidth())
        self.dictionaryComboBox.setSizePolicy(sizePolicy)
        self.dictionaryComboBox.setObjectName("dictionaryComboBox")
        self.dictionaryLayout.addWidget(self.dictionaryComboBox)
        self.gridLayout_4.addLayout(self.dictionaryLayout, 1, 0, 1, 5)
        self.pullRemoteWordsBtn = aqt.qt.QPushButton(self.mainTab)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Fixed, aqt.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pullRemoteWordsBtn.sizePolicy().hasHeightForWidth())
        self.pullRemoteWordsBtn.setSizePolicy(sizePolicy)
        self.pullRemoteWordsBtn.setMinimumSize(aqt.QSize(100, 0))
        self.pullRemoteWordsBtn.setObjectName("pullRemoteWordsBtn")
        self.gridLayout_4.addWidget(self.pullRemoteWordsBtn, 4, 0, 1, 1)
        self.queryBtn = aqt.qt.QPushButton(self.mainTab)
        self.queryBtn.setEnabled(False)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Fixed, aqt.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryBtn.sizePolicy().hasHeightForWidth())
        self.queryBtn.setSizePolicy(sizePolicy)
        self.queryBtn.setMinimumSize(aqt.QSize(100, 0))
        self.queryBtn.setObjectName("queryBtn")
        self.gridLayout_4.addWidget(self.queryBtn, 4, 1, 1, 1)
        self.tabWidget.addTab(self.mainTab, "")
        self.settingTab = aqt.qt.QWidget()
        self.settingTab.setObjectName("settingTab")
        self.gridLayout_2 = aqt.qt.QGridLayout(self.settingTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.defaultConfigGroupBox = aqt.qt.QGroupBox(self.settingTab)
        self.defaultConfigGroupBox.setObjectName("defaultConfigGroupBox")
        self.gridLayout = aqt.qt.QGridLayout(self.defaultConfigGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.sentenceCheckBox = aqt.qt.QCheckBox(self.defaultConfigGroupBox)
        self.sentenceCheckBox.setChecked(True)
        self.sentenceCheckBox.setObjectName("sentenceCheckBox")
        self.gridLayout.addWidget(self.sentenceCheckBox, 0, 1, 1, 1)
        self.definitionCheckBox = aqt.qt.QCheckBox(self.defaultConfigGroupBox)
        self.definitionCheckBox.setChecked(True)
        self.definitionCheckBox.setObjectName("definitionCheckBox")
        self.gridLayout.addWidget(self.definitionCheckBox, 0, 0, 1, 1)
        self.noPronRadioButton = aqt.qt.QRadioButton(self.defaultConfigGroupBox)
        self.noPronRadioButton.setChecked(True)
        self.noPronRadioButton.setObjectName("noPronRadioButton")
        self.gridLayout.addWidget(self.noPronRadioButton, 5, 2, 1, 1)
        self.phraseCheckBox = aqt.qt.QCheckBox(self.defaultConfigGroupBox)
        self.phraseCheckBox.setChecked(True)
        self.phraseCheckBox.setObjectName("phraseCheckBox")
        self.gridLayout.addWidget(self.phraseCheckBox, 0, 2, 1, 1)
        self.BrEPronRadioButton = aqt.qt.QRadioButton(self.defaultConfigGroupBox)
        self.BrEPronRadioButton.setChecked(False)
        self.BrEPronRadioButton.setObjectName("BrEPronRadioButton")
        self.gridLayout.addWidget(self.BrEPronRadioButton, 5, 0, 1, 1)
        self.AmEPronRadioButton = aqt.qt.QRadioButton(self.defaultConfigGroupBox)
        self.AmEPronRadioButton.setObjectName("AmEPronRadioButton")
        self.gridLayout.addWidget(self.AmEPronRadioButton, 5, 1, 1, 1)
        self.BrEPhoneticCheckBox = aqt.qt.QCheckBox(self.defaultConfigGroupBox)
        self.BrEPhoneticCheckBox.setChecked(True)
        self.BrEPhoneticCheckBox.setObjectName("BrEPhoneticCheckBox")
        self.gridLayout.addWidget(self.BrEPhoneticCheckBox, 1, 1, 1, 1)
        self.AmEPhoneticCheckBox = aqt.qt.QCheckBox(self.defaultConfigGroupBox)
        self.AmEPhoneticCheckBox.setChecked(True)
        self.AmEPhoneticCheckBox.setObjectName("AmEPhoneticCheckBox")
        self.gridLayout.addWidget(self.AmEPhoneticCheckBox, 1, 2, 1, 1)
        self.imageCheckBox = aqt.qt.QCheckBox(self.defaultConfigGroupBox)
        self.imageCheckBox.setChecked(True)
        self.imageCheckBox.setObjectName("imageCheckBox")
        self.gridLayout.addWidget(self.imageCheckBox, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.defaultConfigGroupBox, 1, 0, 1, 2)
        self.credentialGroupBox = aqt.qt.QGroupBox(self.settingTab)
        self.credentialGroupBox.setObjectName("credentialGroupBox")
        self.gridLayout_3 = aqt.qt.QGridLayout(self.credentialGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.currentDictionaryLabel = aqt.qt.QLabel(self.credentialGroupBox)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Preferred, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentDictionaryLabel.sizePolicy().hasHeightForWidth())
        self.currentDictionaryLabel.setSizePolicy(sizePolicy)
        self.currentDictionaryLabel.setObjectName("currentDictionaryLabel")
        self.gridLayout_3.addWidget(self.currentDictionaryLabel, 0, 0, 1, 2)
        self.usernameLabel = aqt.qt.QLabel(self.credentialGroupBox)
        self.usernameLabel.setAlignment(aqt.Qt.AlignmentFlag.AlignLeading|aqt.Qt.AlignmentFlag.AlignLeft|aqt.Qt.AlignmentFlag.AlignVCenter)
        self.usernameLabel.setAlignment(aqt.Qt.AlignmentFlag.AlignLeading|aqt.Qt.AlignmentFlag.AlignLeft|aqt.Qt.AlignmentFlag.AlignVCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout_3.addWidget(self.usernameLabel, 1, 0, 1, 1)
        self.usernameLineEdit = aqt.qt.QLineEdit(self.credentialGroupBox)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Expanding, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLineEdit.sizePolicy().hasHeightForWidth())
        self.usernameLineEdit.setSizePolicy(sizePolicy)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout_3.addWidget(self.usernameLineEdit, 1, 1, 1, 1)
        self.passwordLabel = aqt.qt.QLabel(self.credentialGroupBox)
        self.passwordLabel.setAlignment(aqt.Qt.AlignmentFlag.AlignLeading|aqt.Qt.AlignmentFlag.AlignLeft|aqt.Qt.AlignmentFlag.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_3.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.passwordLineEdit = aqt.qt.QLineEdit(self.credentialGroupBox)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Expanding, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit.setSizePolicy(sizePolicy)
        self.passwordLineEdit.setEchoMode(aqt.qt.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_3.addWidget(self.passwordLineEdit, 2, 1, 1, 1)
        self.cookieLabel = aqt.qt.QLabel(self.credentialGroupBox)
        self.cookieLabel.setAlignment(aqt.Qt.AlignmentFlag.AlignLeading|aqt.Qt.AlignmentFlag.AlignLeft|aqt.Qt.AlignmentFlag.AlignVCenter)
        self.cookieLabel.setObjectName("cookieLabel")
        self.gridLayout_3.addWidget(self.cookieLabel, 3, 0, 1, 1)
        self.cookieLineEdit = aqt.qt.QLineEdit(self.credentialGroupBox)
        sizePolicy = aqt.qt.QSizePolicy(aqt.QSizePolicy.Policy.Expanding, aqt.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookieLineEdit.sizePolicy().hasHeightForWidth())
        self.cookieLineEdit.setSizePolicy(sizePolicy)
        self.cookieLineEdit.setClearButtonEnabled(True)
        self.cookieLineEdit.setObjectName("cookieLineEdit")
        self.gridLayout_3.addWidget(self.cookieLineEdit, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.credentialGroupBox, 0, 0, 1, 2)
        self.tabWidget.addTab(self.settingTab, "")
        self.logTab = aqt.qt.QWidget()
        self.logTab.setObjectName("logTab")
        self.tabWidget.addTab(self.logTab, "")
        self.main_layout.addWidget(self.tabWidget)
        self.progressBar = aqt.qt.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.main_layout.addWidget(self.progressBar)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        aqt.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = aqt.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.syncBtn.setText(_translate("Dialog", "开始同步"))
        self.deckLabel.setText(_translate("Dialog", "牌组"))
        self.label.setText(_translate("Dialog", "新单词"))
        self.label_2.setText(_translate("Dialog", "待删除"))
        self.apiLabel.setText(_translate("Dialog", "查询"))
        self.dictionaryLabel.setText(_translate("Dialog", "词典"))
        self.pullRemoteWordsBtn.setText(_translate("Dialog", "获取单词"))
        self.queryBtn.setText(_translate("Dialog", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("Dialog", "同步"))
        self.defaultConfigGroupBox.setTitle(_translate("Dialog", "默认设置"))
        self.sentenceCheckBox.setText(_translate("Dialog", "例句"))
        self.definitionCheckBox.setText(_translate("Dialog", "释义"))
        self.noPronRadioButton.setText(_translate("Dialog", "无发音"))
        self.phraseCheckBox.setText(_translate("Dialog", "短语"))
        self.BrEPronRadioButton.setText(_translate("Dialog", "英式发音"))
        self.AmEPronRadioButton.setText(_translate("Dialog", "美式发音"))
        self.BrEPhoneticCheckBox.setText(_translate("Dialog", "英式英标"))
        self.AmEPhoneticCheckBox.setText(_translate("Dialog", "美式英标"))
        self.imageCheckBox.setText(_translate("Dialog", "图片"))
        self.credentialGroupBox.setTitle(_translate("Dialog", "账号设置"))
        self.currentDictionaryLabel.setText(_translate("Dialog", "当前选择词典: "))
        self.usernameLabel.setText(_translate("Dialog", "账号"))
        self.passwordLabel.setText(_translate("Dialog", "密码"))
        self.cookieLabel.setText(_translate("Dialog", "Cookie"))
        self.cookieLineEdit.setPlaceholderText(_translate("Dialog", "选填"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingTab), _translate("Dialog", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("Dialog", "日志"))

