# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(624, 619)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.logPlainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.logPlainTextEdit.setEnabled(True)
        self.logPlainTextEdit.setObjectName("logPlainTextEdit")
        self.gridLayout.addWidget(self.logPlainTextEdit, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.syncTab = QtWidgets.QWidget()
        self.syncTab.setObjectName("syncTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.syncTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.syncTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.deckComboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckComboBox.sizePolicy().hasHeightForWidth())
        self.deckComboBox.setSizePolicy(sizePolicy)
        self.deckComboBox.setEditable(True)
        self.deckComboBox.setObjectName("deckComboBox")
        self.gridLayout_3.addWidget(self.deckComboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.dictionaryComboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dictionaryComboBox.sizePolicy().hasHeightForWidth())
        self.dictionaryComboBox.setSizePolicy(sizePolicy)
        self.dictionaryComboBox.setObjectName("dictionaryComboBox")
        self.dictionaryComboBox.addItem("")
        self.dictionaryComboBox.addItem("")
        self.gridLayout_3.addWidget(self.dictionaryComboBox, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.syncPushButton = QtWidgets.QPushButton(self.syncTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncPushButton.sizePolicy().hasHeightForWidth())
        self.syncPushButton.setSizePolicy(sizePolicy)
        self.syncPushButton.setMinimumSize(QtCore.QSize(140, 0))
        self.syncPushButton.setObjectName("syncPushButton")
        self.gridLayout_5.addWidget(self.syncPushButton, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.syncTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.imageCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.imageCheckBox.setChecked(True)
        self.imageCheckBox.setObjectName("imageCheckBox")
        self.gridLayout_4.addWidget(self.imageCheckBox, 0, 0, 1, 1)
        self.BrEPhoneticCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.BrEPhoneticCheckBox.setChecked(True)
        self.BrEPhoneticCheckBox.setObjectName("BrEPhoneticCheckBox")
        self.gridLayout_4.addWidget(self.BrEPhoneticCheckBox, 0, 1, 1, 1)
        self.BrEPronCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.BrEPronCheckBox.setChecked(True)
        self.BrEPronCheckBox.setObjectName("BrEPronCheckBox")
        self.gridLayout_4.addWidget(self.BrEPronCheckBox, 0, 2, 1, 1)
        self.sampleCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.sampleCheckBox.setChecked(True)
        self.sampleCheckBox.setObjectName("sampleCheckBox")
        self.gridLayout_4.addWidget(self.sampleCheckBox, 1, 0, 1, 1)
        self.AmEPhoneticCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.AmEPhoneticCheckBox.setObjectName("AmEPhoneticCheckBox")
        self.gridLayout_4.addWidget(self.AmEPhoneticCheckBox, 1, 1, 1, 1)
        self.AmEPronCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.AmEPronCheckBox.setObjectName("AmEPronCheckBox")
        self.gridLayout_4.addWidget(self.AmEPronCheckBox, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 2)
        self.tabWidget.addTab(self.syncTab, "")
        self.accountTab = QtWidgets.QWidget()
        self.accountTab.setObjectName("accountTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.accountTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.accountTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.accountTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.accountTab)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_2.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.accountTab)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout_2.addWidget(self.usernameLineEdit, 0, 1, 1, 1)
        self.tabWidget.addTab(self.accountTab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dict2Anki"))
        self.label_6.setText(_translate("Dialog", "Sync To"))
        self.label.setText(_translate("Dialog", "Dictionary"))
        self.dictionaryComboBox.setItemText(0, _translate("Dialog", "Eudict"))
        self.dictionaryComboBox.setItemText(1, _translate("Dialog", "Youdao"))
        self.syncPushButton.setText(_translate("Dialog", "Start Sync"))
        self.imageCheckBox.setText(_translate("Dialog", "Image"))
        self.BrEPhoneticCheckBox.setText(_translate("Dialog", "British Phonetic"))
        self.BrEPronCheckBox.setText(_translate("Dialog", "British Pronunciation"))
        self.sampleCheckBox.setText(_translate("Dialog", "Sample Sentence"))
        self.AmEPhoneticCheckBox.setText(_translate("Dialog", "American Phonetic"))
        self.AmEPronCheckBox.setText(_translate("Dialog", "American Pronunciation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.syncTab), _translate("Dialog", "Sync"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountTab), _translate("Dialog", "Account"))

