# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dict2anki.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 450)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 12, 10, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.logBox = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logBox.sizePolicy().hasHeightForWidth())
        self.logBox.setSizePolicy(sizePolicy)
        self.logBox.setAutoFillBackground(False)
        self.logBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logBox.setBackgroundVisible(False)
        self.logBox.setObjectName("logBox")
        self.gridLayout.addWidget(self.logBox, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.deckComboBox = QtWidgets.QComboBox(self.tab)
        self.deckComboBox.setEditable(True)
        self.deckComboBox.setObjectName("deckComboBox")
        self.gridLayout_2.addWidget(self.deckComboBox, 0, 1, 1, 1)
        self.dictionaryComboBox = QtWidgets.QComboBox(self.tab)
        self.dictionaryComboBox.setObjectName("dictionaryComboBox")
        self.gridLayout_2.addWidget(self.dictionaryComboBox, 1, 1, 1, 1)
        self.startSyncBtn = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startSyncBtn.sizePolicy().hasHeightForWidth())
        self.startSyncBtn.setSizePolicy(sizePolicy)
        self.startSyncBtn.setMinimumSize(QtCore.QSize(100, 0))
        self.startSyncBtn.setObjectName("startSyncBtn")
        self.gridLayout_2.addWidget(self.startSyncBtn, 0, 2, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 3, 0, 1, 3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.imageCheckBox = QtWidgets.QCheckBox(self.tab)
        self.imageCheckBox.setObjectName("imageCheckBox")
        self.gridLayout_3.addWidget(self.imageCheckBox, 0, 0, 1, 1)
        self.BrEPhoneticCheckBox = QtWidgets.QCheckBox(self.tab)
        self.BrEPhoneticCheckBox.setObjectName("BrEPhoneticCheckBox")
        self.gridLayout_3.addWidget(self.BrEPhoneticCheckBox, 1, 1, 1, 1)
        self.AmEPhoneticCheckBox = QtWidgets.QCheckBox(self.tab)
        self.AmEPhoneticCheckBox.setObjectName("AmEPhoneticCheckBox")
        self.gridLayout_3.addWidget(self.AmEPhoneticCheckBox, 0, 1, 1, 1)
        self.samplesCheckBox = QtWidgets.QCheckBox(self.tab)
        self.samplesCheckBox.setObjectName("samplesCheckBox")
        self.gridLayout_3.addWidget(self.samplesCheckBox, 1, 0, 1, 1)
        self.BrEPronCheckBox = QtWidgets.QCheckBox(self.tab)
        self.BrEPronCheckBox.setObjectName("BrEPronCheckBox")
        self.gridLayout_3.addWidget(self.BrEPronCheckBox, 1, 2, 1, 1)
        self.AmEPronCheckBox = QtWidgets.QCheckBox(self.tab)
        self.AmEPronCheckBox.setObjectName("AmEPronCheckBox")
        self.gridLayout_3.addWidget(self.AmEPronCheckBox, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.username = QtWidgets.QLineEdit(self.tab_2)
        self.username.setObjectName("username")
        self.gridLayout_4.addWidget(self.username, 1, 1, 1, 2)
        self.password = QtWidgets.QLineEdit(self.tab_2)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.gridLayout_4.addWidget(self.password, 2, 1, 1, 2)
        self.currentDictionaryLable = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentDictionaryLable.sizePolicy().hasHeightForWidth())
        self.currentDictionaryLable.setSizePolicy(sizePolicy)
        self.currentDictionaryLable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentDictionaryLable.setObjectName("currentDictionaryLable")
        self.gridLayout_4.addWidget(self.currentDictionaryLable, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dict2Anki"))
        self.label.setText(_translate("Form", "Deck"))
        self.startSyncBtn.setText(_translate("Form", "开始同步"))
        self.label_2.setText(_translate("Form", "词典"))
        self.imageCheckBox.setText(_translate("Form", "图片"))
        self.BrEPhoneticCheckBox.setText(_translate("Form", "英式英标"))
        self.AmEPhoneticCheckBox.setText(_translate("Form", "美式英标"))
        self.samplesCheckBox.setText(_translate("Form", "例句"))
        self.BrEPronCheckBox.setText(_translate("Form", "英式发音"))
        self.AmEPronCheckBox.setText(_translate("Form", "美式发音"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "同步"))
        self.label_4.setText(_translate("Form", "密码"))
        self.label_3.setText(_translate("Form", "账号"))
        self.currentDictionaryLable.setText(_translate("Form", "当前字典："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "登录"))

